"""
MarketPulse - Agent Alpha
Database Module — SQLite setup and operations
"""
import sqlite3
import json
from pathlib import Path
from datetime import datetime
from config import DB_PATH


def get_connection():
    """Get a SQLite connection with row factory."""
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(str(DB_PATH))
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA foreign_keys=ON")
    return conn


def init_db():
    """Initialize all database tables."""
    conn = get_connection()
    cursor = conn.cursor()

    # Portfolio holdings (stocks + MFs)
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS holdings (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            symbol TEXT NOT NULL,
            name TEXT NOT NULL,
            asset_type TEXT NOT NULL CHECK(asset_type IN ('stock', 'mf', 'etf', 'bond', 'gold')),
            exchange TEXT DEFAULT 'NSE',
            quantity REAL NOT NULL,
            buy_price REAL NOT NULL,
            buy_date TEXT NOT NULL,
            invested_amount REAL NOT NULL,
            scheme_code TEXT,
            notes TEXT,
            created_at TEXT DEFAULT (datetime('now')),
            updated_at TEXT DEFAULT (datetime('now'))
        )
    """)

    # Price cache for stocks/indices
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS price_cache (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            symbol TEXT NOT NULL,
            date TEXT NOT NULL,
            open REAL, high REAL, low REAL, close REAL,
            volume INTEGER,
            source TEXT DEFAULT 'yfinance',
            UNIQUE(symbol, date)
        )
    """)

    # MF NAV cache
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS mf_nav_cache (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            scheme_code TEXT NOT NULL,
            date TEXT NOT NULL,
            nav REAL NOT NULL,
            UNIQUE(scheme_code, date)
        )
    """)

    # Signals generated by the system
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS signals (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            symbol TEXT NOT NULL,
            signal_type TEXT NOT NULL CHECK(signal_type IN ('STRONG_BUY', 'BUY', 'HOLD', 'SELL', 'STRONG_SELL')),
            confidence REAL NOT NULL,
            entry_price REAL,
            target_price REAL,
            stop_loss REAL,
            position_size_pct REAL,
            reasoning TEXT,
            factors TEXT,
            created_at TEXT DEFAULT (datetime('now')),
            expiry_date TEXT,
            status TEXT DEFAULT 'active' CHECK(status IN ('active', 'hit_target', 'hit_stoploss', 'expired', 'cancelled'))
        )
    """)

    # ML Predictions
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS ml_predictions (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            symbol TEXT NOT NULL,
            prediction_date TEXT NOT NULL,
            target_horizon_days INTEGER NOT NULL,
            prob_up REAL NOT NULL,
            prob_down REAL NOT NULL,
            expected_return REAL,
            feature_importance TEXT,
            created_at TEXT DEFAULT (datetime('now'))
        )
    """)

    # Paper Trades (Simulated Portfolio)
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS paper_trades (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            symbol TEXT NOT NULL,
            trade_type TEXT NOT NULL CHECK(trade_type IN ('BUY', 'SELL')),
            quantity REAL NOT NULL,
            price REAL NOT NULL,
            fees REAL NOT NULL,
            trade_date TEXT DEFAULT (datetime('now')),
            status TEXT DEFAULT 'OPEN' CHECK(status IN ('OPEN', 'CLOSED')),
            pnl REAL DEFAULT 0,
            notes TEXT
        )
    """)

    # Signal accuracy tracking
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS signal_outcomes (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            signal_id INTEGER NOT NULL,
            outcome TEXT CHECK(outcome IN ('profit', 'loss', 'breakeven', 'pending')),
            actual_return_pct REAL,
            days_held INTEGER,
            closed_at TEXT,
            FOREIGN KEY (signal_id) REFERENCES signals(id)
        )
    """)

    # Daily portfolio snapshots
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS portfolio_snapshots (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            date TEXT NOT NULL UNIQUE,
            total_invested REAL NOT NULL,
            total_current REAL NOT NULL,
            total_return_pct REAL NOT NULL,
            holdings_json TEXT NOT NULL,
            market_data_json TEXT
        )
    """)

    # Watchlist
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS watchlist (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            symbol TEXT NOT NULL UNIQUE,
            name TEXT,
            added_at TEXT DEFAULT (datetime('now')),
            notes TEXT
        )
    """)

    # Market data cache (indices, macro)
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS market_data (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            indicator TEXT NOT NULL,
            date TEXT NOT NULL,
            value REAL NOT NULL,
            source TEXT,
            UNIQUE(indicator, date)
        )
    """)

    conn.commit()
    conn.close()
    print("✅ Database initialized successfully")


# ── CRUD Operations ──────────────────────────────────────────

def add_holding(symbol, name, asset_type, quantity, buy_price, buy_date, invested_amount, exchange="NSE", scheme_code=None, notes=None):
    """Add a new holding to the portfolio."""
    conn = get_connection()
    conn.execute(
        """INSERT INTO holdings (symbol, name, asset_type, exchange, quantity, buy_price, buy_date, invested_amount, scheme_code, notes)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
        (symbol, name, asset_type, exchange, quantity, buy_price, buy_date, invested_amount, scheme_code, notes),
    )
    conn.commit()
    conn.close()


def get_holdings(asset_type=None):
    """Get all holdings, optionally filtered by type."""
    conn = get_connection()
    if asset_type:
        rows = conn.execute("SELECT * FROM holdings WHERE asset_type = ?", (asset_type,)).fetchall()
    else:
        rows = conn.execute("SELECT * FROM holdings ORDER BY asset_type, invested_amount DESC").fetchall()
    conn.close()
    return [dict(r) for r in rows]


def update_holding(holding_id, **kwargs):
    """Update a holding's fields."""
    conn = get_connection()
    allowed = {"quantity", "buy_price", "invested_amount", "notes"}
    updates = {k: v for k, v in kwargs.items() if k in allowed}
    if updates:
        set_clause = ", ".join(f"{k} = ?" for k in updates)
        values = list(updates.values()) + [holding_id]
        conn.execute(f"UPDATE holdings SET {set_clause}, updated_at = datetime('now') WHERE id = ?", values)
        conn.commit()
    conn.close()


def delete_holding(holding_id):
    """Remove a holding."""
    conn = get_connection()
    conn.execute("DELETE FROM holdings WHERE id = ?", (holding_id,))
    conn.commit()
    conn.close()


# ── Paper Trading Operations ──────────────────────────────────────────

def add_paper_trade(symbol, trade_type, quantity, price, fees, notes=None):
    """Record a paper trade."""
    conn = get_connection()
    conn.execute(
        """INSERT INTO paper_trades (symbol, trade_type, quantity, price, fees, notes)
           VALUES (?, ?, ?, ?, ?, ?)""",
        (symbol, trade_type, quantity, price, fees, notes)
    )
    conn.commit()
    conn.close()

def get_paper_portfolio():
    """Calculate current paper trading positions and history."""
    conn = get_connection()
    trades = conn.execute("SELECT * FROM paper_trades ORDER BY trade_date ASC").fetchall()
    conn.close()
    
    positions = {}
    total_realized_pnl = 0
    total_fees = 0
    
    for t in trades:
        t = dict(t)
        sym = t["symbol"]
        qty = t["quantity"]
        price = t["price"]
        ttype = t["trade_type"]
        fees = t["fees"]
        
        total_fees += fees
        
        if sym not in positions:
            positions[sym] = {"symbol": sym, "quantity": 0, "avg_price": 0, "invested": 0}
            
        pos = positions[sym]
        
        if ttype == "BUY":
            total_cost = (pos["quantity"] * pos["avg_price"]) + (qty * price)
            pos["quantity"] += qty
            pos["avg_price"] = total_cost / pos["quantity"] if pos["quantity"] > 0 else 0
            pos["invested"] = pos["quantity"] * pos["avg_price"]
        elif ttype == "SELL":
            if pos["quantity"] >= qty:
                realized_pnl = (price - pos["avg_price"]) * qty
                total_realized_pnl += realized_pnl
                
                pos["quantity"] -= qty
                pos["invested"] = pos["quantity"] * pos["avg_price"]
                
                if pos["quantity"] == 0:
                    pos["avg_price"] = 0
            else:
                pos["quantity"] = 0
                pos["avg_price"] = 0
                pos["invested"] = 0

    active_positions = [p for p in positions.values() if p["quantity"] > 0]
    
    return {
        "positions": active_positions,
        "history": [dict(t) for t in trades][::-1], # Reverse chronological
        "metrics": {
            "realized_pnl": total_realized_pnl,
            "total_fees": total_fees,
            "net_realized_pnl": total_realized_pnl - total_fees
        }
    }


def save_signal(symbol, signal_type, confidence, entry_price=None, target_price=None, stop_loss=None, position_size_pct=None, reasoning=None, factors=None, expiry_date=None):
    """Save a generated signal."""
    conn = get_connection()
    conn.execute(
        """INSERT INTO signals (symbol, signal_type, confidence, entry_price, target_price, stop_loss, position_size_pct, reasoning, factors, expiry_date)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
        (symbol, signal_type, confidence, entry_price, target_price, stop_loss, position_size_pct, reasoning, json.dumps(factors) if factors else None, expiry_date),
    )
    conn.commit()
    conn.close()


def get_active_signals():
    """Get all currently active signals."""
    conn = get_connection()
    rows = conn.execute("SELECT * FROM signals WHERE status = 'active' ORDER BY confidence DESC").fetchall()
    conn.close()
    return [dict(r) for r in rows]


def cache_price(symbol, date, open_p, high, low, close, volume, source="yfinance"):
    """Cache a price data point."""
    conn = get_connection()
    conn.execute(
        """INSERT OR REPLACE INTO price_cache (symbol, date, open, high, low, close, volume, source)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?)""",
        (symbol, date, open_p, high, low, close, volume, source),
    )
    conn.commit()
    conn.close()


def save_portfolio_snapshot(date, total_invested, total_current, total_return_pct, holdings_json, market_data_json=None):
    """Save daily portfolio snapshot."""
    conn = get_connection()
    conn.execute(
        """INSERT OR REPLACE INTO portfolio_snapshots (date, total_invested, total_current, total_return_pct, holdings_json, market_data_json)
           VALUES (?, ?, ?, ?, ?, ?)""",
        (date, total_invested, total_current, total_return_pct, json.dumps(holdings_json), json.dumps(market_data_json) if market_data_json else None),
    )
    conn.commit()
    conn.close()


if __name__ == "__main__":
    init_db()
